import type { LlmClient } from '@/llm/client'
import type { ChatTurn } from '@/llm/protocol'
import {
  DEFAULT_STRATEGY,
  MAX_CORRECTIONS,
  MAX_TOOL_ROUNDS,
  WIND_DOWN_AT,
  type GenerationStrategy,
} from '@/llm/config'
import type { Tool } from '@/tools/types'
import type { GenerationStats } from '@/types'
import {
  FINAL_ANSWER_PROMPT,
  budgetFallback,
  callFingerprint,
  repeatedCallNote,
  rerunsEachCall,
  windDownNote,
} from './budget'
import { parseModelOutput, parsePartial, type ParsedToolCall } from './parse'
import {
  collectEvidence,
  correctionPrompt,
  reviewAnswer,
  type ReviewCheck,
  type ReviewOutcome,
} from './review'

export interface AgentCallbacks {
  /** Fired on every streamed token with the markup already stripped. */
  onPartial: (view: { content: string; reasoning: string; inThinkBlock: boolean }) => void
  onToolStart: (call: ParsedToolCall & { id: string }) => void
  onToolEnd: (id: string, outcome: { result?: string; error?: string; durationMs: number }) => void
  /** Called once per model round so the UI can show intermediate reasoning. */
  onRoundEnd: (round: { content: string; reasoning: string; stats: GenerationStats }) => void
  /**
   * The answer check rejected a draft and a correction is being generated. The
   * reply the user is watching is about to be replaced, so say why.
   */
  onCorrection?: (found: ReviewCheck[]) => void
}

export interface AgentResult {
  content: string
  reasoning: string
  stats: GenerationStats
  /** What the answer check made of this turn. */
  review?: ReviewOutcome
  /**
   * True when the tool budget ran out and this answer came from the wind-down
   * round rather than from the model deciding it had finished. The reply is as
   * good as what the tools had returned by then, and nothing more, so the
   * interface says so instead of presenting it as a settled answer.
   */
  windDown?: boolean
}

export interface AgentOptions {
  /** How reasoning is budgeted. Defaults to whatever `config.ts` ships. */
  strategy?: GenerationStrategy
  /** Check the answer before returning it. On unless the eval turns it off. */
  review?: boolean
}

/**
 * The model often spends a whole turn inside the think block and stops without
 * restating its conclusion. Leaving that answer hidden would show the user an
 * empty reply and, worse, push an empty assistant message into the history, so
 * the next turn loses the context. Treat the reasoning as the answer instead.
 */
function promoteReasoningIfEmpty(result: AgentResult): AgentResult {
  if (result.content || !result.reasoning) return result
  return { ...result, content: result.reasoning, reasoning: '' }
}

/** The draft an answer check rejected, kept so a worse correction can be dropped. */
interface Draft {
  result: AgentResult
  found: ReviewCheck[]
}

/**
 * Decides which of the two answers the user gets, and what to say about it.
 *
 * A correction has to earn its place. It is generated by the same 0.8B model
 * that produced the draft, so it can perfectly well arrive shorter, emptier, or
 * with a fresh problem in place of the old one — and the checks can see that.
 * Fewer problems than the draft wins; anything else and the draft stands, which
 * makes the mechanism unable to leave an answer worse than it found it.
 *
 * `corrected` is claimed only for an answer that now passes every check, and
 * `found` otherwise describes what is still wrong with the text being shown.
 * A half-fixed answer advertised as corrected would be the one outcome here
 * worse than no check at all.
 */
function settle(latest: AgentResult, remaining: ReviewCheck[], draft: Draft | null): AgentResult {
  if (!draft) return { ...latest, review: { found: remaining, corrected: false } }

  const improved = latest.content !== '' && remaining.length < draft.found.length
  if (!improved) return { ...draft.result, review: { found: draft.found, corrected: false } }

  return remaining.length === 0
    ? { ...latest, review: { found: draft.found, corrected: true } }
    : { ...latest, review: { found: remaining, corrected: false } }
}

/**
 * Runs generate → execute tools → generate again until the model answers without
 * requesting a tool.
 *
 * Spending the round budget is not one of the ways this ends. When the last
 * round is gone the tools are withheld and the model is asked to conclude from
 * what they returned, so a turn that searched four times still says what it
 * found — see `src/agent/budget.ts` for why that replaced giving up.
 *
 * Every answer then goes through `reviewAnswer` before it is returned, and a
 * failed check costs one more generation to put right. That pass is not
 * optional and not routed: a skill fires on some requests, this runs on all of
 * them.
 */
export async function runAgent(
  client: LlmClient,
  turns: ChatTurn[],
  tools: Tool[],
  callbacks: AgentCallbacks,
  options: AgentOptions = {},
): Promise<AgentResult> {
  const byName = new Map(tools.map((tool) => [tool.schema.function.name, tool]))
  const schemas = tools.map((tool) => tool.schema)
  const conversation = [...turns]
  const strategy = options.strategy ?? DEFAULT_STRATEGY
  const checking = options.review ?? true
  const evidence = collectEvidence(turns)

  let last: AgentResult = {
    content: '',
    reasoning: '',
    stats: { tokens: 0, thinkTokens: 0, durationMs: 0, tokensPerSecond: 0 },
  }
  let draft: Draft | null = null
  let corrections = 0

  // Only a round that asked for a tool spends the budget. A correction round
  // adds one generation of its own, capped separately by `MAX_CORRECTIONS`.
  let toolRounds = 0
  /** Set once the budget is gone, and never unset: from here the turn answers. */
  let windDown = false
  /** Every call already made this turn, so none of them is made twice. */
  const executed = new Map<string, string>()

  for (;;) {
    if (!windDown && toolRounds >= MAX_TOOL_ROUNDS) {
      windDown = true
      conversation.push({ role: 'user', content: FINAL_ANSWER_PROMPT })
    }

    let raw = ''
    // Withholding the schemas is what makes this the last round: the chat
    // template then renders no tool block, so there is no call format to copy.
    const generation = await client.generate(conversation, windDown ? [] : schemas, {
      strategy,
      onChunk: (chunk) => {
        raw += chunk
        callbacks.onPartial(parsePartial(raw))
      },
    })

    const parsed = parseModelOutput(generation.text || raw)
    const stats: GenerationStats = {
      tokens: generation.tokens,
      thinkTokens: generation.thinkTokens,
      durationMs: generation.durationMs,
      tokensPerSecond: generation.durationMs > 0 ? (generation.tokens / generation.durationMs) * 1000 : 0,
    }
    // A model that asks for a tool anyway once they are gone is asking for
    // something nothing can run, so the request is dropped and the round counts
    // as the answer it was meant to be.
    const toolCalls = windDown ? [] : parsed.toolCalls
    const outcome = { content: parsed.content, reasoning: parsed.reasoning, stats }
    // Only when the turn is over: before a tool call, reasoning is just reasoning.
    last = toolCalls.length === 0 ? promoteReasoningIfEmpty(outcome) : outcome
    callbacks.onRoundEnd(last)

    if (toolCalls.length === 0) {
      const findings = checking ? reviewAnswer(last.content, evidence) : []
      const found = findings.map((finding) => finding.check)

      if (findings.length === 0 || corrections >= MAX_CORRECTIONS) {
        const answer = settle(last, found, draft)
        if (!windDown) return answer
        // The round that had to answer produced nothing, and `settle` found no
        // earlier draft to fall back on. What the tools did return is worth
        // more than the apology this used to end on. Substituted after the
        // check rather than before it, because deterministic text assembled
        // from tool results has nothing for a correction round to fix.
        return { ...answer, content: answer.content || budgetFallback(evidence), windDown: true }
      }

      corrections += 1
      draft = { result: last, found }
      callbacks.onCorrection?.(found)
      // The draft goes back without its reasoning: what needs fixing is the
      // answer the user would have seen, and reasoning is never fed back.
      conversation.push({ role: 'assistant', content: last.content })
      conversation.push({ role: 'user', content: correctionPrompt(findings) })
      continue
    }

    // Echo the assistant's tool request back so the model sees its own decision.
    conversation.push({ role: 'assistant', content: generation.text || raw })

    for (const call of toolCalls) {
      const id = crypto.randomUUID()
      callbacks.onToolStart({ ...call, id })
      const startedAt = performance.now()
      const tool = byName.get(call.name)

      if (!tool) {
        const error = `Unknown tool "${call.name}". Available tools: ${[...byName.keys()].join(', ')}`
        callbacks.onToolEnd(id, { error, durationMs: performance.now() - startedAt })
        conversation.push({ role: 'tool', content: error })
        continue
      }

      // Running a search again would spend a network request, a rate-limit
      // slot and part of the budget to arrive at text already in the
      // conversation. The clock is the exception: the same place a minute
      // later is a new reading, so `current_time` is always executed.
      const fingerprint = callFingerprint(call.name, call.arguments)
      const earlier = rerunsEachCall(call.name) ? undefined : executed.get(fingerprint)
      if (earlier !== undefined) {
        const note = repeatedCallNote(call.name, earlier)
        callbacks.onToolEnd(id, { result: note, durationMs: performance.now() - startedAt })
        conversation.push({ role: 'tool', content: note })
        continue
      }

      try {
        const result = await tool.execute(call.arguments)
        executed.set(fingerprint, result)
        callbacks.onToolEnd(id, { result, durationMs: performance.now() - startedAt })
        conversation.push({ role: 'tool', content: result })
        // Only what a tool actually returned is evidence. A failure has nothing
        // to check an answer against, and demanding a citation for a page that
        // never loaded would be worse than saying nothing.
        evidence.toolResults.push({ tool: call.name, result })
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error)
        callbacks.onToolEnd(id, { error: message, durationMs: performance.now() - startedAt })
        conversation.push({ role: 'tool', content: `Tool "${call.name}" failed: ${message}` })
      }
    }

    toolRounds += 1

    // Said after the results and before the next decision, which is the only
    // place it can change what the model does with the round it has left.
    const remaining = MAX_TOOL_ROUNDS - toolRounds
    if (remaining > 0 && remaining <= WIND_DOWN_AT) {
      conversation.push({ role: 'user', content: windDownNote(remaining) })
    }
  }
}
